import { colors } from '../../utils/colors';
import { StyleSheet } from 'react-native';
import { scale } from '../../utils/scale';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: scale(16),
    paddingVertical: scale(12),
    borderBottomWidth: 1,
    borderBottomColor: colors.background,
    paddingTop: scale(50),
  },
  backButton: {
    width: scale(40),
    height: scale(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    fontSize: scale(28),
    color: colors.blue.highlight,
  },
  headerSpacer: {
    width: scale(40),
  },
  waveFormContainer: {
    height: scale(150),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  loadingContainer: {
    padding: scale(16),
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    marginTop: scale(8),
    fontSize: scale(14),
    color: colors.text.secondary,
  },
  messagesContainer: {
    flex: 1,
    backgroundColor: colors.white,
  },
  messagesContent: {
    paddingVertical: scale(16),
  },
  textInputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: scale(16),
    paddingVertical: scale(12),
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderTopColor: colors.blue.medium,
  },
  textInput: {
    flex: 1,
    maxHeight: scale(100),
    backgroundColor: colors.white,
    borderRadius: scale(20),
    paddingHorizontal: scale(16),
    paddingVertical: scale(10),
    fontSize: scale(16),
    marginRight: scale(8),
  },
  sendButton: {
    backgroundColor: colors.blue.highlight,
    borderRadius: scale(20),
    paddingHorizontal: scale(20),
    paddingVertical: scale(10),
    justifyContent: 'center',
    alignItems: 'center',
  },
  sendButtonText: {
    color: colors.white,
    fontSize: scale(16),
    fontWeight: '600',
  },
  actionButtonsContainer: {
    paddingHorizontal: scale(16),
    paddingVertical: scale(12),
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.background,
  },
  sendAnswerButton: {
    backgroundColor: colors.blue.highlight,
    borderRadius: scale(24),
    paddingVertical: scale(14),
    justifyContent: 'center',
    alignItems: 'center',
  },
  sendAnswerButtonText: {
    color: colors.white,
    fontSize: scale(16),
    fontWeight: '600',
  },
  controlsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: scale(32),
    paddingVertical: scale(24),
    paddingBottom: scale(40),
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.background,
  },
  keyboardButton: {
    width: scale(56),
    height: scale(56),
    borderRadius: scale(28),
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.blue.highlight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  keyboardIcon: {
    fontSize: scale(24),
  },
  micButton: {
    width: scale(80),
    height: scale(80),
    borderRadius: scale(40),
    backgroundColor: colors.blue.highlight,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  micButtonActive: {
    backgroundColor: '#E53935',
  },
  micIcon: {
    fontSize: scale(32),
  },
  finishButton: {
    paddingHorizontal: scale(24),
    paddingVertical: scale(12),
    borderRadius: scale(24),
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.blue.highlight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  finishButtonText: {
    color: colors.blue.highlight,
    fontSize: scale(16),
    fontWeight: '600',
  },
});
